---
- name: Check if Helm is installed.
  ansible.builtin.command: which helm
  failed_when: false
  changed_when: false
  check_mode: false
  register: helm_command_results

- name: Download Helm Install Script.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: 0775
  when: helm_command_results.rc == 1

- name: Run Helm install Script.
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_command_results.rc == 1